import type { EditorialBand, EditorialHero } from './types';

export const accessibilityLayer = {
  path: '/accessibility-layer',
  seoTitle: 'Bizooma Accessibility Layer — ADA & WCAG Monitoring Powered by AI',
  seoDescription: 'Continuous ADA & WCAG compliance monitoring with an AI-powered accessibility widget, automated scans, and audit-ready reports.',
  hero: {
    eyebrow: 'PRODUCTS',
    title: 'Bizooma Accessibility Layer',
    lede: 'Continuous ADA and WCAG compliance monitoring.',
    sub: 'Protect your business, improve usability, and monitor accessibility issues in real time with the Bizooma Accessibility Layer.',
    cta: { label: 'Get the widget – $25/mo', href: '/accessibility/signup' },
    secondaryCta: { label: 'Schedule Demo', href: 'https://calendly.com/joe-bizooma/30min', external: true },
  } satisfies EditorialHero,
  features: {
    title: 'What it does',
    intro: 'A drop-in widget for your visitors and a dashboard for your team — backed by an AI engine that explains every fix.',
    groups: [
      { title: 'Visual Accessibility', items: ['Font size & spacing', 'Dyslexia-friendly font', 'High contrast & dark mode', 'Grayscale & invert', 'Highlight links & headings'] },
      { title: 'Navigation', items: ['Keyboard navigation', 'Skip-to-content', 'Focus enhancement', 'Reading guide & mask', 'Pause animations'] },
      { title: 'AI Enhancements', items: ['AI alt text suggestions', 'Readability scoring', 'Contrast detection', 'Heading structure analysis', 'Plain-English fixes'] },
      { title: 'Compliance', items: ['WCAG 2.1 AA tracking', 'ADA readiness score', 'Section 508 indicators', 'Downloadable audit reports', 'Public statement page'] },
    ],
  },
  widget: {
    eyebrow: 'The Widget',
    title: 'A floating accessibility panel for every visitor',
    paragraph: 'Install with one line of HTML. Visitors get instant control over font size, contrast, motion, dyslexia-friendly fonts, reading guides, and more — fully white-label on Agency & Enterprise plans.',
    snippet: `<script src="https://widget.bizooma.com/accessibility.js"\n        data-site-id="YOUR_SITE_ID" async></script>`,
    panelTitle: 'Accessibility',
    panelSub: 'Powered by Bizooma',
    panelOptions: ['Larger text', 'High contrast', 'Dyslexia font', 'Reduce motion', 'Highlight links', 'Reading guide'],
  },
  dashboard: {
    eyebrow: 'The Dashboard',
    title: 'See compliance health at a glance',
    paragraph: 'Run scans, triage issues by severity & WCAG criterion, assign fixes to developers, and generate audit-ready reports — all from one dashboard.',
    items: ['Real-time accessibility scoring', 'Issues with AI-generated fixes & code examples', 'Multi-client agency mode', 'PDF compliance reports & public statements'],
    cta: { label: 'Get started', href: '/accessibility/signup' },
    mock: { title: 'Accessibility score', range: 'Last 30d', tiles: [{ label: 'Score', value: '92' }, { label: 'WCAG AA', value: '87%' }, { label: 'Critical', value: '3' }] },
    mockCaption: 'Example interface with sample data — not reported results.',
  },
  audience: {
    title: "Who it's for",
    paragraphs: ['Any organization whose website needs to work for every visitor and stand up to ADA, WCAG 2.1 AA, Section 508 and EAA requirements.', 'Agencies can white-label the widget and reports on Agency and Enterprise plans.'],
  } satisfies EditorialBand,
  pricing: {
    title: 'Simple, transparent pricing',
    intro: 'One plan to get your site accessible today. Cancel anytime.',
    badge: 'Launch plan',
    plan: 'Bizooma Accessibility Widget',
    price: '$25',
    period: '/month',
    tagline: 'Everything you need to ship an accessible site.',
    items: ['1 website', 'Embeddable accessibility widget', 'Automated WCAG scans', 'AI-powered remediation tips', 'Issue tracking dashboard', 'Cancel anytime'],
    cta: { label: 'Get started', href: '/accessibility/signup' },
    footnote: 'More plans coming soon.',
  },
  faqTitle: 'Frequently asked',
  faqs: [
    { q: 'What laws does this help me comply with?', a: 'WCAG 2.1 AA, the ADA (Title III), Section 508, and EAA. Our reports map findings to the relevant criteria.' },
    { q: 'Will the widget slow my site down?', a: 'No. The widget is a small async script (<25KB gzipped) that loads after the main thread is idle.' },
    { q: 'Do I need to change my code?', a: 'The widget improves accessibility at runtime without code changes. Scanner findings include suggested code fixes you can apply when ready.' },
    { q: 'Can agencies white-label this?', a: 'Yes. Agency and Enterprise plans include white-label widget branding and reports.' },
  ],
  cta: {
    title: 'Make every visitor feel welcome',
    paragraph: 'Get an instant accessibility score for your site and see exactly what to fix.',
    label: 'Get the widget – $25/mo',
    href: '/accessibility/signup',
  },
  privacy: {
    eyebrow: 'Privacy & Compliance',
    title: 'Your privacy matters',
    paragraph: 'The Bizooma Accessibility Layer is designed to respect every visitor. The widget collects only the minimal, anonymized usage signals required to deliver accessibility features and produce compliance reports. We never sell personal information, and your dashboard data stays scoped to your organization.',
    tags: ['GDPR aware', 'ADA Title III', 'WCAG 2.1 AA', 'Section 508'],
    ccpaLabel: 'California Consumer Privacy Act (CCPA)',
    cpraLabel: 'California Privacy Rights Act (CPRA)',
  },
};
